### ISSUE TITLE
Project skeleton

### ISSUE THREAD

**Issue by llorllale** [llorllale/go-gitlint#1]

**Comment by llorllale** [comment]
Done in efc2c7605f0c331f0939ba311ae760a9c27762e9

**Comment by llorllale** [comment]
golangci-lint failing ([log](https://travis-ci.org/llorllale/go-gitlint/builds/494057948)) - opened issue golangci/golangci-lint#395

**Comment by llorllale** [comment]
Fixed in e2498b8ab269a7cb1a3a97f470dfc7096b80a5cb

**Comment by 0pdd** [comment]
@llorllale the puzzle [#3](https://github.com/llorllale/go-gitlint/issues/3) is still not solved.
